language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="vchan"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - DEPOPTS="mirage-xen xen-gnt-unix xen-evtchn-unix"
 matrix:
   - DISTRO=fedora-24 OCAML_VERSION=4.03.0
