language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
 - OCAML_VERSION=4.01 PACKAGE=vchan DEPOPTS="mirage-xen xen-gnt xen-evtchn"
 - OCAML_VERSION=latest PACKAGE=vchan DEPOPTS="mirage-xen xen-gnt xen-evtchn"
